### Creating ndarrays

In [2]:
import numpy as np

In [4]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [5]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [6]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [7]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2.ndim

2

In [12]:
arr2.shape

(2, 4)

In [13]:
# arr2.shape (2, 4) which means that the array has 2 dimensions,
# where the first dimension has 2 elements and the second has 4.

In [10]:
arr1.dtype

dtype('float64')

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3, 6))
# the array has 2 dimensions, where the first dimension has 3 elements and the second has 6.

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.empty((2, 3, 2))    # Returns a new array of given shape and type, without initializing entries(garbage values).
                       # the array has 3 dimensions, where the first dimension has 2 elements, the second has 3
                       # and the third has 2

array([[[4.67404522e-310, 0.00000000e+000],
        [2.37663529e-312, 2.56761491e-312],
        [8.48798317e-313, 9.33678148e-313]],

       [[1.08221785e-312, 6.79038653e-313],
        [8.70018275e-313, 8.16639523e-043],
        [2.49172955e+180, 2.57037074e+184]]])

In [17]:
arr2d = np.array([[1, 2, 3],[4,5, 6], [7, 8, 9]])
arr2d.shape

(1, 3, 3)